---
title: "Calculation of Evaluation Metrics and Plotting Predictions"
author:
- name: "Setareh Kazemi Kheiri ^[Email: skazemik@buffalo.edu]"
  affiliation: Department of Industrial and Systems Engineering, University at Buffalo
  
- name: "Hongyue Sun ^[Email: hongyuesun@uga.edu | Phone: +1-706-542-2329 | Website: <a href=\"https://engineering.uga.edu/team_member/hongyue-sun\">University  of Georgia Official</a> ]"
  affiliation: College of Engineering, University of Georgia
    
- name: "Fadel Megahed ^[Email: megahefm@miamioh.edu | Phone: +1-513-529-4185 | Website: <a href=\"https://miamioh.edu/fsb/directory/?up=/directory/megahefm\">Miami University Official</a> ]"
  affiliation: Farmer School of Business, Miami University
    
- name: "Lora Cavuoto ^[Email: loracavu@buffalo.edu | Phone: +1-716-645-4696 | Website: <a href=\"https://engineering.buffalo.edu/home/research/faculty/profiles.host.html/content/shared/engineering/industrial-systems/profiles/faculty/cavuoto-lora.html\">University at Buffalo Official</a> ]"
  affiliation: Department of Industrial and Systems Engineering, University at Buffalo

date: "`r format(Sys.time(), '%B %d, %Y')`"
bibliography: refs.bib
link-citations: true
header-includes:
  - \usepackage{booktabs}
  - \usepackage{chngpage}
  - \usepackage{caption}
  - \usepackage{chngpage}
  - \usepackage{color}
  - \usepackage[autostyle=true,english=american]{csquotes}
  - \usepackage{csvsimple}
  - \usepackage{framed}
  - \usepackage{graphicx}
  - \usepackage{hyperref}
  - \usepackage{lineno}
  - \usepackage{lscape}
  - \usepackage{mathptmx}
  - \usepackage{mathrsfs}
  - \usepackage{makecell}
  - \usepackage{mathtools}
  - \usepackage{media9}
  - \usepackage{multicol}
  - \usepackage{multirow}
  - \usepackage{secdot}
  - \usepackage{sectsty}
  - \usepackage{setspace}
  - \usepackage{subcaption}
  - \usepackage{tabulary}
  - \usepackage{titlesec}
  - \usepackage[colorinlistoftodos]{todonotes}
  - \usepackage{url}

output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyr, dplyr, ggplot2, brms)

```

## Load Data

```{r load_data, cache=TRUE}

model_fxd_pc <- readRDS("~/Library/CloudStorage/Box-Box/NIOSH R21 Warehousing Project Docs/Code/reliability_analysis/output/model_fxd_pc.rds")

model_fxd <- readRDS("~/Library/CloudStorage/Box-Box/NIOSH R21 Warehousing Project Docs/Code/reliability_analysis/output/model_fxd.rds")

model_rnds_pc <- readRDS("~/Library/CloudStorage/Box-Box/NIOSH R21 Warehousing Project Docs/Code/reliability_analysis/output/model_rnds_pc.rds")

model_rnds <- readRDS("~/Library/CloudStorage/Box-Box/NIOSH R21 Warehousing Project Docs/Code/reliability_analysis/output/model_rnds.rds")

load("~/Library/CloudStorage/Box-Box/NIOSH R21 Warehousing Project Docs/Code/reliability_analysis/main_df.RData")

```

## Prepare Data

```{r prep_data, cache=TRUE}

models <- list(model_fxd_pc, model_fxd,model_rnds_pc, model_rnds)
names(models) <- c("model_fxd_pc", "model_fxd", "model_rnds_pc", "model_rnds")

rm(model_fxd_pc, model_fxd,model_rnds_pc, model_rnds)
  
sub_con_uniq <- unique(main_df$sub_con)

resid_fxd <- vector(mode = "list", length = 43)
names(resid_fxd) <- sub_con_uniq

resid_fxd_pc <- vector(mode = "list", length = 43)
names(resid_fxd_pc) <- sub_con_uniq

resid_rnds <- vector(mode = "list", length = 43)
names(resid_rnds) <- sub_con_uniq

resid_rnds_pc <- vector(mode = "list", length = 43)
names(resid_fxd_pc) <- sub_con_uniq

resid <- list(resid_fxd_pc, resid_fxd, resid_rnds_pc, resid_rnds)

names(resid) <- c("resid_fxd_pc", "resid_fxd", "resid_rnds_pc", "resid_rnds")

rm(resid_fxd_pc, resid_fxd, resid_rnds_pc, resid_rnds)

pred <- resid

names(pred) <- c("pred_fxd_pc", "pred_fxd", "pred_rnds_pc", "pred_rnds")

time_unique <- seq(10,40, by=5)

main_df$Gender <- as.numeric(main_df$Gender)

main_df$Gender[main_df$Gender==1]<-0
main_df$Gender[main_df$Gender==2]<-1

```

## Extract Residuals and Predicted values

```{r extract, cache=TRUE}

for (q in  (1:4)){
  for ( j in 1:length(sub_con_uniq)){
    
    rows_to_train <-  which(main_df$sub_con != sub_con_uniq[j] )
    train_data_1 <- main_df[rows_to_train,]
    
    test_data_1 <- main_df[-rows_to_train,]
    actuals1 <- test_data_1$RPE
    
    pred[[q]][[j]][[1]] <- apply(posterior_predict(models[[q]][[j]][[1]], newdata = test_data_1), 2, mean)
    
    pred[[q]][[j]][[1]][pred[[q]][[j]][[1]] > 10] <- 10
    
    pred[[q]][[j]][[1]][pred[[q]][[j]][[1]] < 0] <- 0
    
    resid[[q]][[j]][[1]] <- actuals1 - pred[[q]][[j]][[1]]
    
    for (i in 1:length(time_unique)){
      
      rows_to_update <-  which(main_df$sub_con == sub_con_uniq[j] & main_df$time <= time_unique[i] )
      
      rows_to_test <-  which(test_data_1$time > time_unique[i] )
      
      train_data_2 <- main_df[rows_to_update,]
      
      test_data <- test_data_1[rows_to_test,1:31]
      
      actuals <- actuals1[rows_to_test]
      
      if(q==3|q==4){
        train_data_2$new_Intercept <- 1
        train_data_2$new_time <- train_data_2$time
        
        test_data$new_Intercept <- 1
        test_data$new_time <- test_data$time
        
        # Adjust train_data for Gender
        
        train_df2_len <- dim(train_data_2)[1]
        train_data_2[(train_df2_len+1), ] <- NA
        
        train_data_2[(train_df2_len+1),"Gender"] <-  ifelse(train_data_2$Gender[1] == 1, 0, 1)
        
        train_data_2$sub_con[(train_df2_len+1)] <- "seudo_sub"
        train_data_2$subject[(train_df2_len+1)] <- "seudo"
        
        train_data_2[(train_df2_len+1),which(is.na(train_data_2[(train_df2_len+1),]))] <- 0
        
        }
      
      pred[[q]][[j]][[i+1]] <- apply(posterior_predict(models[[q]][[j]][[i+2]], newdata = test_data,allow_new_levels = TRUE), 2, mean)
      
      pred[[q]][[j]][[i+1]][pred[[q]][[j]][[i+1]] > 10] <- 10
      
      pred[[q]][[j]][[i+1]][pred[[q]][[j]][[i+1]] < 0] <- 0
      
      resid[[q]][[j]][[i+1]] <- actuals - pred[[q]][[j]][[i+1]]
      
    }
  }
}
    
rm(models)

```

## Evaluate prediction metrics

```{r evalmetrisc, cache=TRUE}

perc <- c(0,round(seq(10, 40, by = 5) / 45, 2))
time_vec <- c(seq(0,45,by=5), seq(15,45,by=5), seq(20,45,by=5), seq(25,45,by=5), seq(30,45,by=5), seq(35,45,by=5), seq(40,45,by=5), 45)

rpe <- main_df[,c(1,2,8)] %>% 
  pivot_wider(names_from = "time", values_from = "RPE")

rpe_mean <- matrix(NA, nrow = 43, ncol = 11)

for(i in 1:43){
  rpe_mean[i,1] <- rpe$sub_con[i]
  
  rpe_mean[i,2:11] <- colMeans(rpe[-i,2:11])
}

colnames(rpe_mean) <- colnames(rpe)

rpe_mean <- as.data.frame(rpe_mean) %>%
  pivot_longer(-1, names_to = "time", values_to = "rpe_mean")

rpe_mean$rpe_mean <- round(as.numeric(rpe_mean$rpe_mean),2)
rpe_mean$time <- as.numeric(rpe_mean$time)

resid_main <- resid
pred_main <- pred

metric_func  <- function(resid,pred, main_df, perc, time_vec){
  
  resid_names <- names(resid)
  
  for (i in seq_along(resid)) {
    for (j in seq_along(resid[[i]])) {
      resid[[i]][[j]] <- data.frame(resid = resid[[i]][[j]])
      resid[[i]][[j]]$perc <- perc[j]
    }
    resid[[i]] <- do.call(rbind, resid[[i]])
  }
  
  for (i in seq_along(pred)) {
    for (j in seq_along(pred[[i]])) {
      pred[[i]][[j]] <- data.frame(pred = pred[[i]][[j]])
      pred[[i]][[j]]$perc <- perc[j]
    }
    pred[[i]] <- do.call(rbind, pred[[i]])
  }
  
  # names(resid_rnds_AR1) <- sub_con_uniq
  
  for (i in seq_along(resid)) {
    resid[[i]]$sub_con <- names(resid)[i]
  }
  
  for (i in seq_along(pred)) {
    pred[[i]]$sub_con <- names(pred)[i]
  }
  
  resid_long <- do.call(rbind, resid)
  
  pred_long <- do.call(rbind, pred)
  
  lngt <- length(resid)
  
  resid_long$time <- rep(time_vec, lngt)
  pred_long$time <- rep(time_vec, lngt)
  
  resid_long <- left_join(resid_long,pred_long, by = c("sub_con", "time","perc"))
  
  resid_long <- left_join(resid_long, main_df[,c("sub_con", "time", "RPE")], by = c("sub_con", "time"))
  
  resid_long <- left_join(resid_long, rpe_mean, by = c("sub_con", "time"))
  
  resid_long$ae_pred <- abs(resid_long$RPE - resid_long$pred)
  
  if (any(!(resid_long$ae_pred==abs(resid_long$resid)))){
    "Warning: Discrepancy between the model's predictions and the ones calculated from model residuals"}
  
  resid_long$ae_mean <- abs(resid_long$RPE - resid_long$rpe_mean)
  
  
  resid2 <- vector(mode = "list", length = 43)
  names(resid2) <- resid_names
  
  mase <- matrix(NA, nrow = 43, ncol = 8)
  mae <- matrix(NA, nrow = 43, ncol = 8)
  
  for(j in 1:43){
    resid2[[j]] <- vector(mode = "list", length = 8)
  }
  
  for(i in 1:43){
    for (j in 1:8){
      resid2[[i]][[j]] <- resid_long[which(resid_long$sub_con == resid_names[i] & resid_long$perc == perc[j]),]
     
      row_num <- dim(resid2[[i]][[j]])[1]
      
      mase[i,j] <- sum(resid2[[i]][[j]]$ae_pred)/sum(resid2[[i]][[j]]$ae_mean)
      
      mae[i,j] <- mean(resid2[[i]][[j]]$ae_pred, na.rm = T)
    }
  }
  
  se_col <- function(x) apply(x, 2, function(col) sd(col, na.rm = TRUE) / sqrt(sum(!is.na(col))))
  
  metrics_res <- data.frame(mean_mae = colMeans(mae, na.rm = T), se_mae = se_col(mae) , mean_mase = colMeans(mase[-c(28,42),], na.rm = T), se_mase = se_col(mase[-c(28,42),])) 
  rownames(metrics_res) <- perc
  
  
  res_list <- list(resid = resid2, metrics_res = metrics_res)
  
  return(res_list)
}

metrics_fx_pc <- metric_func(resid_main[[1]], pred_main[[1]], main_df, perc, time_vec)
metrics_fx <- metric_func(resid_main[[2]], pred_main[[2]], main_df, perc, time_vec)
metrics_mx_pc <- metric_func(resid_main[[3]], pred_main[[3]], main_df, perc, time_vec)
metrics_mx <- metric_func(resid_main[[4]], pred_main[[4]], main_df, perc, time_vec)

```

## Prediction plots

```{r predplots, cache=TRUE}

custom_colors <- c(
  "0.RPE" = "#000000",
  "22.RPE" = "#000000",   # Fixed color for type = RPE
  "33.RPE" = "#000000",
  "44.RPE" = "#000000",
  "56.RPE" = "#000000",
  "67.RPE" = "#000000",
  "78.RPE" = "#000000",
  "89.RPE" = "#000000",
  "0.pred" ="#999999",
  "22.pred" ="#0072B2",
  "33.pred" = "#56B4E9", # Different colors for type = pred
  "44.pred" = "#009E73",
  "56.pred" = "#D55E00",
  "67.pred" = "#E69F00",
  "78.pred" = "purple",
  "89.pred" = "magenta"
)

pred <- pred_main[[2]]

long2plot_func <- function(pred, main_df, perc, time_vec, var_name){
  
  perc2 <- perc*100 
  
  for (i in seq_along(pred)) {
    for (j in seq_along(pred[[i]])) {
      pred[[i]][[j]] <- data.frame(pred = pred[[i]][[j]])
      pred[[i]][[j]]$perc <- perc2[j]
    }
    pred[[i]] <- do.call(rbind, pred[[i]])
  }
  
  for (i in seq_along(pred)) {
    pred[[i]]$sub_con <- names(pred)[i]
  }
  
  pred_long <- do.call(rbind, pred)
  
  lngt <- length(pred)
  
  pred_long$time <- rep(time_vec, lngt)
  
  pred_long <- left_join(pred_long, main_df[,c("sub_con", "time", "RPE")], by = c("sub_con", "time"))
  
  pred_long <- pivot_longer(pred_long, cols = c(1,5), names_to = "type", values_to = "value")
  
  plot_act_fc <- ggplot(pred_long[which(pred_long$sub_con=="Sub15-2.5-10"|pred_long$sub_con=="Sub15-2.5-15"|pred_long$sub_con=="Sub17-2.5-10"|pred_long$sub_con=="Sub17-2.5-15"),], 
                        aes(x = time, y = value, group = interaction(sub_con, perc, type), color = interaction(perc, type))) +
    geom_point() +
    geom_line() +
    facet_wrap(~ sub_con, scales = "free_y") +
    labs(title = paste0("Actual RPE Vs. Fitted RPE For Each Round of Model ", var_name),
         x = "Time",
         y = "RPE") +
    theme_minimal() + 
    scale_color_manual(values = custom_colors) +
    theme(text = element_text(size = 18),
          plot.title = element_text(size = 18, face = "bold"),     
          axis.title = element_text(size = 18),                    
          axis.text = element_text(size = 14),                     
          legend.title = element_text(size = 18),                
          legend.text = element_text(size = 16)) 

  
  return(plot_act_fc)
}

plot_act_fc <-  vector(mode = "list", length = 4)
names(plot_act_fc) <- names(pred_main)

model_name <- c("Fixed Effects With Nonlinear Function of Time", "Fixed Effects With Linear Function of Time", "Mixed Effects With Nonlinear Function of Time", "Mixed Effects With Linear Function of Time")

for (p in 1:4){
  
  plot_act_fc[[p]] <- long2plot_func(pred_main[[p]], main_df, perc, time_vec, model_name[p])

}

# Plotting for all models

for (i in seq_along(plot_act_fc)){
  
  model_name <- names(plot_act_fc)[i]
  
  cat(paste0("## Model ",model_name, " \n\n"))
  
  print(plot_act_fc[[i]])
  
  cat("\n\n")
}

```


